name: "Hello"

on:
  pull_request:
    types: [opened, synchronize, closed, reopened, edited]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          regex: "^.*Title[\\s\\S]+Description[\\s\\S]+$"
