name: "Hello"

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          regex: "^.*Title.+Description.+$"
